//firebase_options.dart
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDf3IDU95InU3zaTMO89-XwJGWyBez6nXQ',
    appId: '1:1029279907270:web:9b81eb7a9600a5882646c7',
    messagingSenderId: '1029279907270',
    projectId: 'nerdenevar-ef803',
    authDomain: 'nerdenevar-ef803.firebaseapp.com',
    storageBucket: 'nerdenevar-ef803.firebasestorage.app',
    measurementId: 'G-EP9V9TLFK9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCrJP8GZ2mcnxozfY5wIudZdpvMlVHReI',
    appId: '1:1029279907270:android:88503af42c2e128a2646c7',
    messagingSenderId: '1029279907270',
    projectId: 'nerdenevar-ef803',
    storageBucket: 'nerdenevar-ef803.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJUUP4LRO0vZLMGzWOeQnJ3cfl89vKnG8',
    appId: '1:1029279907270:ios:6ec1b21cc801d3f12646c7',
    messagingSenderId: '1029279907270',
    projectId: 'nerdenevar-ef803',
    storageBucket: 'nerdenevar-ef803.firebasestorage.app',
    iosBundleId: 'com.example.proje',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJUUP4LRO0vZLMGzWOeQnJ3cfl89vKnG8',
    appId: '1:1029279907270:ios:6ec1b21cc801d3f12646c7',
    messagingSenderId: '1029279907270',
    projectId: 'nerdenevar-ef803',
    storageBucket: 'nerdenevar-ef803.firebasestorage.app',
    iosBundleId: 'com.example.proje',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDf3IDU95InU3zaTMO89-XwJGWyBez6nXQ',
    appId: '1:1029279907270:web:03ba83e4fdd88e102646c7',
    messagingSenderId: '1029279907270',
    projectId: 'nerdenevar-ef803',
    authDomain: 'nerdenevar-ef803.firebaseapp.com',
    storageBucket: 'nerdenevar-ef803.firebasestorage.app',
    measurementId: 'G-WSHSGNKL29',
  );

}