//firebase_options.dart
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACIR-Tph77U_WJs_ruw87-TCDsyJMY388',
    appId: '1:673486542066:web:55502c48ec0d45f5c66c6b',
    messagingSenderId: '673486542066',
    projectId: 'proje-62d4c',
    authDomain: 'proje-62d4c.firebaseapp.com',
    storageBucket: 'proje-62d4c.firebasestorage.app',
    measurementId: 'G-GT1JJYRZ41',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBU7P1Tux_WewG9ko9_25FAWSFdweX7eb8',
    appId: '1:673486542066:android:b0bd1f0bd5bb74eac66c6b',
    messagingSenderId: '673486542066',
    projectId: 'proje-62d4c',
    storageBucket: 'proje-62d4c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBgDsWTCCLRdEVhEiBReN-wYtoIQyEOwk',
    appId: '1:673486542066:ios:2c6cdb4c3efea479c66c6b',
    messagingSenderId: '673486542066',
    projectId: 'proje-62d4c',
    storageBucket: 'proje-62d4c.firebasestorage.app',
    iosBundleId: 'com.example.proje',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBgDsWTCCLRdEVhEiBReN-wYtoIQyEOwk',
    appId: '1:673486542066:ios:2c6cdb4c3efea479c66c6b',
    messagingSenderId: '673486542066',
    projectId: 'proje-62d4c',
    storageBucket: 'proje-62d4c.firebasestorage.app',
    iosBundleId: 'com.example.proje',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACIR-Tph77U_WJs_ruw87-TCDsyJMY388',
    appId: '1:673486542066:web:92ab1d4b1d6a39dac66c6b',
    messagingSenderId: '673486542066',
    projectId: 'proje-62d4c',
    authDomain: 'proje-62d4c.firebaseapp.com',
    storageBucket: 'proje-62d4c.firebasestorage.app',
    measurementId: 'G-WD7N78RS7Y',
  );
}
